### ISSUE TITLE
Trigger Key

### ISSUE THREAD

**Issue by yasinsil** [Speedi13/ROP-COMPILER#10]
Hello. I want to ask a question. 

https://github.com/Speedi13/ROP-COMPILER/blob/master/CSGO-Triggerbot-Tutorial.md

I want to use toggle trigger key (on-off), is it possible ? If possible, can you help?

Thanks.

**Comment by Speedi13** [comment]
> I want to use toggle trigger key (on-off), is it possible ? If possible, can you help?
It is possible but you need to change the code of the triggerbot script.

**Comment by davide9800** [comment]
how i should change it?

**Comment by davide9800** [comment]
no help?
