### ISSUE TITLE
45/50 stuck

### ISSUE THREAD

**Issue by eakmadashma** [Speedi13/ROP-COMPILER#13]
![image](https://user-images.githubusercontent.com/55052643/77210816-ce5fb080-6af9-11ea-9366-441ab9ddf473.png)

**Comment by eakmadashma** [comment]
doesnt do anything after that

**Comment by Speedi13** [comment]
Please look at this issue
https://github.com/Speedi13/ROP-COMPILER/issues/14
Another guy seems to have the same problem
