### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dezziee** [Speedi13/ROP-COMPILER#14]
![Capture](https://user-images.githubusercontent.com/62452238/77215180-a298f680-6b0a-11ea-9104-9f0f2f1293a7.PNG)
I've downloaded everything needed but when trying to load up the csgo_minimap it stops at the point in the picture also noticed that its named 'aaaaaaaa' etc. instead of random letters or numbers

**Comment by Speedi13** [comment]
What CPU do you use?
Does it support RDRAND? If not it might be a bit slower.

Is the title always called 'aaaaaaaa'?
Does it work without running VMProtect on the file?

**Comment by Dezziee** [comment]
I have a Ryzen 5 3600X, it says it is supported in the screenshot but even so i've left it running throughout a whole game and it hasnt changed. The first few times i tried to load it up i didnt use VMProtect and it has always been named 'aaaaaa'. I've reset my PC as i needed to do it anyway and tried it on VMProtect but still have the same issue.

**Comment by Speedi13** [comment]
What windows 10 version are you using? [Start "winver.exe"]

Maybe try to run my runtime installer: https://github.com/Speedi13/RuntimeInstaller/releases/download/1/VsRuntimesInstaller.zip

What AntiVirus do you use? Maybe try to disable that. [Some AntiViruses have issues with the trigger bot script]

**Comment by Dezziee** [comment]
The version is 1909, i've run the runtime installer and tried it but it hasnt made a difference and i dont have any AntiVirus enabled.

**Comment by Speedi13** [comment]
Did you try running it as Administrator?

Does this happen with all scripts? or only certain ones?

**Comment by Dezziee** [comment]
I've not tried any other script, but yeah i've ran it on admin but doesnt make a difference.

**Comment by Speedi13** [comment]
Strange, it must be the Random number generator.
It seems take a very long time to generate a random filled buffer for some reason.

On my test PC i had that issue with the Dual-Elliptic-Curve random number generator so I disabled it in the code.

But because your CPU supports Hardware random number generation it should only stick to that.

Maybe do you have HyperV enabled? Make sure to disable HyperV.
Also disable this "Core Isolation"
![image](https://user-images.githubusercontent.com/17367538/77257113-8e700900-6c72-11ea-87b0-1ce24f5dd463.png)

**Comment by Dezziee** [comment]
I don't have core isolaton supported and dont have HyperV enabled or cant  find it.

**Comment by Speedi13** [comment]
> dont have HyperV enabled or cant find it.
https://www.isunshare.com/blog/how-to-disable-or-turn-off-hyper-v-in-windows-10-four-options/#option1

Would it be ok if I compile a version with more debug output and upload it here to send to you?
Because I can't figure the issue out any other way.

**Comment by Dezziee** [comment]
yeah sure

**Comment by Speedi13** [comment]
[RopCompiler_debug1.zip](https://github.com/Speedi13/ROP-COMPILER/files/4366274/RopCompiler_debug1.zip)

Try to this build and post a screenshot of the result

**Comment by Dezziee** [comment]
![image](https://user-images.githubusercontent.com/62452238/77259585-540a6a00-6c7a-11ea-854b-e4d9be3444dc.png)

**Comment by Speedi13** [comment]
lol ok, its the random number generator but not in a way I thought.

As seen in the title, it always outputs the same I guess.
That will be an issue.

I now disabled the Hardware random number generator.


Try now please.
[RopCompiler_debug2.zip](https://github.com/Speedi13/ROP-COMPILER/files/4366317/RopCompiler_debug2.zip)

**Comment by Dezziee** [comment]
Yeah thank you so much, it works. The name came up with random letters and numbers etc and its loading the gadgets and then came up with the end message. Gonna try it out ingame now thanks for your help i really appreciate it.

**Comment by Speedi13** [comment]
I added a check for that.
Please try if this version works. If it works I will upload it to unknowncheats ;)

[Speedis_RopCompiler_v1.1.zip](https://github.com/Speedi13/ROP-COMPILER/files/4366396/Speedis_RopCompiler_v1.1.zip)

**Comment by Dezziee** [comment]
Yeah the other version work fine in game and i've just added it and searching for a game now.

**Comment by Dezziee** [comment]
Works completely perfect, havent tried trigger or esp but dont think that matters. Thanks again

**Comment by Speedi13** [comment]
Thank you for helping.
I posted the update on UC ;)
https://www.unknowncheats.me/forum/cs-go-releases/351009-rop-csgo-cheat-glow-minimap-triggerbot-16.html#post2728843
