### ISSUE TITLE
glow thickness

### ISSUE THREAD

**Issue by aarpii** [Speedi13/ROP-COMPILER#21]
how to edit glow to make thick?

**Comment by Speedi13** [comment]
You have to adjust this number:
https://github.com/Speedi13/ROP-COMPILER/blob/master/CheatSourceCodes/CSGO_GlowESP.asm#L124

Look at my UC post:
https://www.unknowncheats.me/forum/2555980-post26.html

**Comment by aarpii** [comment]
Thanks Speedi,

Are you planning to expand this with any more functions? Like aimbot, no flash, no smoke or something?

**Comment by Speedi13** [comment]
No that is too much work.
Remember it would all have to be written in assembler and with only a very limited instruction set.
