### ISSUE TITLE
has the new update blocked the hack?

### ISSUE THREAD

**Issue by legend696** [Speedi13/ROP-COMPILER#23]
i always use glow and minimap for csgo so  i can troll but it did not work today right after i update the game, but i was using it 3 hour before the update came out. so i was thinking i might be the update that blocks the hack.

**Comment by jackieyiwu** [comment]
same problem

**Comment by realtriz** [comment]
Yep same problem.. it detects the game id and then stuck.

**Comment by legend696** [comment]
ya....

**Comment by Malivas** [comment]
Still no word on how to fix it?

**Comment by legend696** [comment]
nope

**Comment by Malivas** [comment]
It didn't work for several users

**Comment by jackieyiwu** [comment]
while ( GetRemoteProcessModuleInfo( ProcessId, L"client_panorama.dll", &ClientDllInfo ) != true ) in main.cpp  change client_panorama.dll to client.dll   done  now its working for me!

**Comment by Speedi13** [comment]
I added a fix to the source code.
https://github.com/Speedi13/ROP-COMPILER/commit/e3b705452fb3a1976df09bd6951639561e97db58

I will release an update to UC later ;)

**Comment by Speedi13** [comment]
I posted the updated files:
https://www.unknowncheats.me/forum/2819822-post419.html

**Comment by Malivas** [comment]
[image: image.png]

**Comment by Malivas** [comment]
![image](https://user-images.githubusercontent.com/31177668/83806693-81e14580-a6e4-11ea-89fb-fc83c74dfa7a.png)

**Comment by realtriz** [comment]
Nice ty
