### ISSUE TITLE
glow on teammates

### ISSUE THREAD

**Issue by Suspycat** [Speedi13/ROP-COMPILER#32]
Hello there!
I know I may sound like a begging kid and maybe I am, but I would be really grateful if you could tell me how to achieve glow on teammates. I have tried to implement another "if" to check if the given person is in my team, but haven't succeeded, I am not experienced with this language. 
Thank you in advance and sorry for disturbing you with this.

**Comment by Speedi13** [comment]
Here you go:
https://gist.github.com/Speedi13/bc5e5b8729ec9a8cc11293d330232d4f

It works by instead of skipping when the players are on the local team it jumps to `l_teammates`

**Comment by Suspycat** [comment]
Thank you so much!
